export const systData = {
    schlID: '0303001',
    systST: true,
    mdulID: '',
    mdulST: true,
    acadAY: '',
    acadSD: '',
    acadND: '',
    acadSM: '',
    acadQT: '',
};

export const axisData = {
    axisAY: '',
    axisID: '',
    axisNM: '',
    axisDC: '',
    axisDT: '',
};

export const axonData = {
    axonAY: '',
    axonID: '',
    axonNM: '',
    axonDC: '',
    axonDT: '',
};

export const prntData = {
    prntID: '',
    prntUN: '',
    prntPW: '',
    prntST: '',
    prntFP: '',
    prntLN: '',
    prntFN: '',
    prntMN: '',
    prntC1: '',
    prntC2: '',
    prntC3: '',
    prntC4: '',
    prntC5: '',
    prntC6: '',
    prntC7: '',
    prntC8: '',
    prntC9: '',
};

export const userData = {
    userID: '',
    userCL: '',
    userST: false,
    userOL: false,
    userFP: false,
    userUN: '',
    userPW: '',
    userDP: '',
    userAY: '',
    userSM: '',
    userYR: '',
    userSC: '',
    userLR: '',
    userLN: '',
    userFN: '',
    userMN: '',
    userSF: '',
    userSX: '',
    userCN: 0,
    userAD: '',
    userFA: '',
    userMA: '',
    userGA: '',
    userEC: 0,
    userCP: '',
    userCR: '',
    userPR: '',
};


export const userHlth = {
    userP1: '',
    userP2: '',
    userP3: '',
    userP4: '',
    userP5: '',
    userP6: '',
};

export const userReqs = {
    userR1: '',
    userR2: '',
    userR3: '',
    userR4: '',
    userR5: '',
    userR6: '',
    userR7: '',
    userR8: '',
};

export const userSchd = {
    // monday
    usrM00: '',
    usrM01: '',
    usrM02: '',
    usrM03: '',
    usrM04: '',
    usrM05: '',
    usrM06: '',
    usrM07: '',
    usrM08: '',
    usrM09: '',
    usrM10: '',
    usrM11: '',
    usrM12: '',
    usrM13: '',
    usrM14: '',
    // tuesday
    usrT00: '',
    usrT01: '',
    usrT02: '',
    usrT03: '',
    usrT04: '',
    usrT05: '',
    usrT06: '',
    usrT07: '',
    usrT08: '',
    usrT09: '',
    usrT10: '',
    usrT11: '',
    usrT12: '',
    usrT13: '',
    usrT14: '',
    // wednesday
    usrW00: '',
    usrW01: '',
    usrW02: '',
    usrW03: '',
    usrW04: '',
    usrW05: '',
    usrW06: '',
    usrW07: '',
    usrW08: '',
    usrW09: '',
    usrW10: '',
    usrW11: '',
    usrW12: '',
    usrW13: '',
    usrW14: '',
    // thursday
    usrH00: '',
    usrH01: '',
    usrH02: '',
    usrH03: '',
    usrH04: '',
    usrH05: '',
    usrH06: '',
    usrH07: '',
    usrH08: '',
    usrH09: '',
    usrH10: '',
    usrH11: '',
    usrH12: '',
    usrH13: '',
    usrH14: '',
    // friday
    usrF00: '',
    usrF01: '',
    usrF02: '',
    usrF03: '',
    usrF04: '',
    usrF05: '',
    usrF06: '',
    usrF07: '',
    usrF08: '',
    usrF09: '',
    usrF10: '',
    usrF11: '',
    usrF12: '',
    usrF13: '',
    usrF14: '',
};

export const popuData = {
    // grade levels
    totG01: 0,
    totG02: 0,
    totG03: 0,
    totG04: 0,
    totG05: 0,
    totG06: 0,
    totG07: 0,
    totG08: 0,
    totG09: 0,
    totG10: 0,
    totG11: 0,
    totG12: 0,
    // males
    totM01: 0,
    totM02: 0,
    totM03: 0,
    totM04: 0,
    totM05: 0,
    totM06: 0,
    totM07: 0,
    totM08: 0,
    totM09: 0,
    totM10: 0,
    totM11: 0,
    totM12: 0,
    // females
    totF01: 0,
    totF02: 0,
    totF03: 0,
    totF04: 0,
    totF05: 0,
    totF06: 0,
    totF07: 0,
    totF08: 0,
    totF09: 0,
    totF10: 0,
    totF11: 0,
    totF12: 0,
    // misc
    totAPL: 0,
    totSTP: 0,
};

export const sectData = {
    sectAY: '',
    sectID: '',
    sectCL: '',
    sectNM: '',
    sectYR: '',
    sectAV: '',
    sectML: '',
    sectFL: '',
};

export const sectSchd = {
    // monday
    sctM00: '',
    sctM01: '',
    sctM02: '',
    sctM03: '',
    sctM04: '',
    sctM05: '',
    sctM06: '',
    sctM07: '',
    sctM08: '',
    sctM09: '',
    sctM10: '',
    sctM11: '',
    sctM12: '',
    sctM13: '',
    sctM14: '',
    // tuesday
    sctT00: '',
    sctT01: '',
    sctT02: '',
    sctT03: '',
    sctT04: '',
    sctT05: '',
    sctT06: '',
    sctT07: '',
    sctT08: '',
    sctT09: '',
    sctT10: '',
    sctT11: '',
    sctT12: '',
    sctT13: '',
    sctT14: '',
    // wednesday
    sctW00: '',
    sctW01: '',
    sctW02: '',
    sctW03: '',
    sctW04: '',
    sctW05: '',
    sctW06: '',
    sctW07: '',
    sctW08: '',
    sctW09: '',
    sctW10: '',
    sctW11: '',
    sctW12: '',
    sctW13: '',
    sctW14: '',
    // thursday
    sctH00: '',
    sctH01: '',
    sctH02: '',
    sctH03: '',
    sctH04: '',
    sctH05: '',
    sctH06: '',
    sctH07: '',
    sctH08: '',
    sctH09: '',
    sctH10: '',
    sctH11: '',
    sctH12: '',
    sctH13: '',
    sctH14: '',
    // friday
    sctF00: '',
    sctF01: '',
    sctF02: '',
    sctF03: '',
    sctF04: '',
    sctF05: '',
    sctF06: '',
    sctF07: '',
    sctF08: '',
    sctF09: '',
    sctF10: '',
    sctF11: '',
    sctF12: '',
    sctF13: '',
    sctF14: '',
};

export const subjData = {
    subjAY: '',
    subjID: '',
    subjNM: '',
    subjTC: '',
    subjND: '',
    subjMN: '',
};


export const gradData = {
    gradAY: '',
    gradID: '',
    gradON: '',
    gradOF: '',
    gradQ1: '',
    gradQ2: '',
    gradQ3: '',
    gradQ4: '',
    gradFN: '',
    gradAV: '',
};

export const tranData = {
    tranAY: '',
    tranID: '',
    tranCL: '',
    tranNM: '',
    tranDC: '',
    tranAM: '',
    tranPY: '',
    tranRF: '',
    tranBY: '',
    tranAG: '',
    tranCG: '',
    tranST: '',
};

export const bullData = {
    postAY: '',
    postID: '',
    postCL: '',
    postNM: '',
    postDC: '',
    postBY: '',
    postTO: '',
    postSD: '',
    postED: '',
};

export const librData = {
    bookAY: '',
    bookID: '',
    bookST: '',
    bookNM: '',
    bookAU: '',
    bookBR: '',
};

export const hlthData = {
    hlthAY: '',
    hlthID: '',
    hlthNM: '',
    hlthYR: '',
    hlthSC: '',
    hlthRS: '',
    hlthRC: '',
    hlthMD: '',
};

export const probData = {
    probAY: '',
    probID: '',
    probNM: '',
    probDC: '',
    probST: '',
    probBY: '',
};

export const loclData = {
    loclID: '',
    loclCL: '',
    loclFN: '',
    loclNM: '',
    loclTM: '',
};
